using Microsoft.AspNetCore.Mvc;

namespace TestAPIS.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpGet(Name = "GetWeatherForecast")]
        public IEnumerable<WeatherForecast> Get()
        {
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
        }

        [HttpGet]
        [Route("Movies")]
        public IActionResult GetMovies()
        {
            List<string> Movies = new List<string>();
            string Harry01 = "{\"Title\":\"Harry Potter and the Sorcerer's Stone\",\"Year\":\"2001\",\"Rated\":\"PG\",\"Released\":\"16 Nov 2001\",\"Runtime\":\"152 min\",\"Genre\":\"Adventure, Family, Fantasy\",\"Director\":\"Chris Columbus\",\"Writer\":\"J.K. Rowling, Steve Kloves\",\"Actors\":\"Daniel Radcliffe, Rupert Grint, Richard Harris\",\"Plot\":\"An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.\",\"Language\":\"English, Latin\",\"Country\":\"United Kingdom, United States\",\"Awards\":\"Nominated for 3 Oscars. 17 wins & 68 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNjQ3NWNlNmQtMTE5ZS00MDdmLTlkZjUtZTBlM2UxMGFiMTU3XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"7.6/10\"},{\"Source\":\"Rotten Tomatoes\",\"Value\":\"81%\"},{\"Source\":\"Metacritic\",\"Value\":\"65/100\"}],\"Metascore\":\"65\",\"imdbRating\":\"7.6\",\"imdbVotes\":\"734,590\",\"imdbID\":\"tt0241527\",\"Type\":\"movie\",\"DVD\":\"28 May 2002\",\"BoxOffice\":\"$318,087,620\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"},\n{\"Title\":\"Harry Potter and the Chamber of Secrets\",\"Year\":\"2002\",\"Rated\":\"PG\",\"Released\":\"15 Nov 2002\",\"Runtime\":\"161 min\",\"Genre\":\"Adventure, Family, Fantasy\",\"Director\":\"Chris Columbus\",\"Writer\":\"J.K. Rowling, Steve Kloves\",\"Actors\":\"Daniel Radcliffe, Rupert Grint, Emma Watson\",\"Plot\":\"An ancient prophecy seems to be coming true when a mysterious presence begins stalking the corridors of a school of magic and leaving its victims paralyzed.\",\"Language\":\"English, Latin\",\"Country\":\"United Kingdom, United States\",\"Awards\":\"Won 1 BAFTA Film Award13 wins & 46 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTcxODgwMDkxNV5BMl5BanBnXkFtZTYwMDk2MDg3._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"7.4/10\"},{\"Source\":\"Rotten Tomatoes\",\"Value\":\"82%\"},{\"Source\":\"Metacritic\",\"Value\":\"63/100\"}],\"Metascore\":\"63\",\"imdbRating\":\"7.4\",\"imdbVotes\":\"602,413\",\"imdbID\":\"tt0295297\",\"Type\":\"movie\",\"DVD\":\"11 Apr 2003\",\"BoxOffice\":\"$262,450,136\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}";
            string Harry02 = "\"Title\":\"Harry Potter and the Chamber of Secrets\",\"Year\":\"2002\",\"Rated\":\"PG\",\"Released\":\"15 Nov 2002\",\"Runtime\":\"161 min\",\"Genre\":\"Adventure, Family, Fantasy\",\"Director\":\"Chris Columbus\",\"Writer\":\"J.K. Rowling, Steve Kloves\",\"Actors\":\"Daniel Radcliffe, Rupert Grint, Emma Watson\",\"Plot\":\"An ancient prophecy seems to be coming true when a mysterious presence begins stalking the corridors of a school of magic and leaving its victims paralyzed.\",\"Language\":\"English, Latin\",\"Country\":\"United Kingdom, United States\",\"Awards\":\"Won 1 BAFTA Film Award13 wins & 46 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTcxODgwMDkxNV5BMl5BanBnXkFtZTYwMDk2MDg3._V1_SX300.jpg\",\"Ratings\":[{ \"Source\":\"Internet Movie Database\",\"Value\":\"7.4/10\"},{ \"Source\":\"Rotten Tomatoes\",\"Value\":\"82%\"},{ \"Source\":\"Metacritic\",\"Value\":\"63/100\"}],\"Metascore\":\"63\",\"imdbRating\":\"7.4\",\"imdbVotes\":\"602,413\",\"imdbID\":\"tt0295297\",\"Type\":\"movie\",\"DVD\":\"11 Apr 2003\",\"BoxOffice\":\"$262,450,136\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"";
            string Harry03 = "\"Title\":\"Harry Potter and the Prisoner of Azkaban\",\"Year\":\"2004\",\"Rated\":\"PG\",\"Released\":\"04 Jun 2004\",\"Runtime\":\"142 min\",\"Genre\":\"Adventure, Family, Fantasy\",\"Director\":\"Alfonso Cuarón\",\"Writer\":\"J.K. Rowling, Steve Kloves\",\"Actors\":\"Daniel Radcliffe, Emma Watson, Rupert Grint\",\"Plot\":\"Harry Potter, Ron and Hermione return to Hogwarts School of Witchcraft and Wizardry for their third year of study, where they delve into the mystery surrounding an escaped prisoner who poses a dangerous threat to the young wizard.\",\"Language\":\"English, Latin, Old English\",\"Country\":\"United Kingdom, United States\",\"Awards\":\"Nominated for 2 Oscars. 17 wins & 53 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTY4NTIwODg0N15BMl5BanBnXkFtZTcwOTc0MjEzMw@@._V1_SX300.jpg\",\"Ratings\":[{ \"Source\":\"Internet Movie Database\",\"Value\":\"7.9/10\"},{ \"Source\":\"Rotten Tomatoes\",\"Value\":\"90%\"},{ \"Source\":\"Metacritic\",\"Value\":\"82/100\"}],\"Metascore\":\"82\",\"imdbRating\":\"7.9\",\"imdbVotes\":\"601,274\",\"imdbID\":\"tt0304141\",\"Type\":\"movie\",\"DVD\":\"23 Nov 2004\",\"BoxOffice\":\"$249,975,996\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"";
            string Harry04 = "\"Title\":\"Harry Potter and the Goblet of Fire\",\"Year\":\"2005\",\"Rated\":\"PG-13\",\"Released\":\"18 Nov 2005\",\"Runtime\":\"157 min\",\"Genre\":\"Adventure, Family, Fantasy\",\"Director\":\"Mike Newell\",\"Writer\":\"Steve Kloves, J.K. Rowling\",\"Actors\":\"Daniel Radcliffe, Emma Watson, Rupert Grint\",\"Plot\":\"Harry Potter finds himself competing in a hazardous tournament between rival schools of magic, but he is distracted by recurring nightmares.\",\"Language\":\"English, French, Latin\",\"Country\":\"United Kingdom, United States\",\"Awards\":\"Nominated for 1 Oscar. 13 wins & 44 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTI1NDMyMjExOF5BMl5BanBnXkFtZTcwOTc4MjQzMQ@@._V1_SX300.jpg\",\"Ratings\":[{ \"Source\":\"Internet Movie Database\",\"Value\":\"7.7/10\"},{ \"Source\":\"Rotten Tomatoes\",\"Value\":\"88%\"},{ \"Source\":\"Metacritic\",\"Value\":\"81/100\"}],\"Metascore\":\"81\",\"imdbRating\":\"7.7\",\"imdbVotes\":\"594,990\",\"imdbID\":\"tt0330373\",\"Type\":\"movie\",\"DVD\":\"07 Mar 2006\",\"BoxOffice\":\"$290,417,905\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"";
            string Harry05 = "\"Title\":\"Harry Potter and the Order of the Phoenix\",\"Year\":\"2007\",\"Rated\":\"PG-13\",\"Released\":\"11 Jul 2007\",\"Runtime\":\"138 min\",\"Genre\":\"Action, Adventure, Family\",\"Director\":\"David Yates\",\"Writer\":\"Michael Goldenberg, J.K. Rowling\",\"Actors\":\"Daniel Radcliffe, Emma Watson, Rupert Grint\",\"Plot\":\"With their warning about Lord Voldemort's return scoffed at, Harry and Dumbledore are targeted by the Wizard authorities as an authoritarian bureaucrat slowly seizes power at Hogwarts.\",\"Language\":\"English, Latin\",\"Country\":\"United Kingdom, United States\",\"Awards\":\"Nominated for 2 BAFTA Film 17 wins & 47 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTM0NTczMTUzOV5BMl5BanBnXkFtZTYwMzIxNTg3._V1_SX300.jpg\",\"Ratings\":[{ \"Source\":\"Internet Movie Database\",\"Value\":\"7.5/10\"},{ \"Source\":\"Rotten Tomatoes\",\"Value\":\"78%\"},{ \"Source\":\"Metacritic\",\"Value\":\"71/100\"}],\"Metascore\":\"71\",\"imdbRating\":\"7.5\",\"imdbVotes\":\"553,288\",\"imdbID\":\"tt0373889\",\"Type\":\"movie\",\"DVD\":\"11 Dec 2007\",\"BoxOffice\":\"$292,353,413\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"";
            string Harry06 = "\"Title\":\"Harry Potter and the Half-Blood Prince\",\"Year\":\"2009\",\"Rated\":\"PG\",\"Released\":\"15 Jul 2009\",\"Runtime\":\"153 min\",\"Genre\":\"Action, Adventure, Family\",\"Director\":\"David Yates\",\"Writer\":\"Steve Kloves, J.K. Rowling\",\"Actors\":\"Daniel Radcliffe, Emma Watson, Rupert Grint\",\"Plot\":\"As Harry Potter begins his sixth year at Hogwarts, he discovers an old book marked as \\\"the property of the Half-Blood Prince\\\" and begins to learn more about Lord Voldemort's dark past.\",\"Language\":\"English, Latin\",\"Country\":\"United Kingdom, United States\",\"Awards\":\"Nominated for 1 Oscar. 9 wins & 39 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNzU3NDg4NTAyNV5BMl5BanBnXkFtZTcwOTg2ODg1Mg@@._V1_SX300.jpg\",\"Ratings\":[{ \"Source\":\"Internet Movie Database\",\"Value\":\"7.6/10\"},{ \"Source\":\"Rotten Tomatoes\",\"Value\":\"84%\"},{ \"Source\":\"Metacritic\",\"Value\":\"78/100\"}],\"Metascore\":\"78\",\"imdbRating\":\"7.6\",\"imdbVotes\":\"517,495\",\"imdbID\":\"tt0417741\",\"Type\":\"movie\",\"DVD\":\"08 Dec 2009\",\"BoxOffice\":\"$302,305,431\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"";
            string Harry07 = "\"Title\":\"Harry Potter and the Deathly Hallows: Part 1\",\"Year\":\"2010\",\"Rated\":\"PG-13\",\"Released\":\"19 Nov 2010\",\"Runtime\":\"146 min\",\"Genre\":\"Adventure, Family, Fantasy\",\"Director\":\"David Yates\",\"Writer\":\"Steve Kloves, J.K. Rowling\",\"Actors\":\"Daniel Radcliffe, Emma Watson, Rupert Grint\",\"Plot\":\"As Harry, Ron, and Hermione race against time and evil to destroy the Horcruxes, they uncover the existence of the three most powerful objects in the wizarding world: the Deathly Hallows.\",\"Language\":\"English, Latin\",\"Country\":\"United Kingdom, United States\",\"Awards\":\"Nominated for 2 Oscars. 15 wins & 55 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTQ2OTE1Mjk0N15BMl5BanBnXkFtZTcwODE3MDAwNA@@._V1_SX300.jpg\",\"Ratings\":[{ \"Source\":\"Internet Movie Database\",\"Value\":\"7.7/10\"},{ \"Source\":\"Rotten Tomatoes\",\"Value\":\"77%\"},{ \"Source\":\"Metacritic\",\"Value\":\"65/100\"}],\"Metascore\":\"65\",\"imdbRating\":\"7.7\",\"imdbVotes\":\"519,635\",\"imdbID\":\"tt0926084\",\"Type\":\"movie\",\"DVD\":\"08 Dec 2009\",\"BoxOffice\":\"$296,347,721\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"";
            string Harry08 = "\"Title\":\"Harry Potter and the Deathly Hallows: Part 2\",\"Year\":\"2011\",\"Rated\":\"PG-13\",\"Released\":\"15 Jul 2011\",\"Runtime\":\"130 min\",\"Genre\":\"Adventure, Fantasy, Mystery\",\"Director\":\"David Yates\",\"Writer\":\"Steve Kloves, J.K. Rowling\",\"Actors\":\"Daniel Radcliffe, Emma Watson, Rupert Grint\",\"Plot\":\"Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.\",\"Language\":\"English, Latin\",\"Country\":\"United Kingdom, United States\",\"Awards\":\"Nominated for 3 Oscars. 46 wins & 94 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg\",\"Ratings\":[{ \"Source\":\"Internet Movie Database\",\"Value\":\"8.1/10\"},{ \"Source\":\"Rotten Tomatoes\",\"Value\":\"96%\"},{ \"Source\":\"Metacritic\",\"Value\":\"85/100\"}],\"Metascore\":\"85\",\"imdbRating\":\"8.1\",\"imdbVotes\":\"827,211\",\"imdbID\":\"tt1201607\",\"Type\":\"movie\",\"DVD\":\"11 Nov 2011\",\"BoxOffice\":\"$381,409,310\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"";
            string Resident01 = "\"Title\":\"Resident Evil\",\"Year\":\"2002\",\"Rated\":\"R\",\"Released\":\"15 Mar 2002\",\"Runtime\":\"100 min\",\"Genre\":\"Action, Horror, Sci-Fi\",\"Director\":\"Paul W.S. Anderson\",\"Writer\":\"Paul W.S. Anderson\",\"Actors\":\"Milla Jovovich, Michelle Rodriguez, Ryan McCluskey\",\"Plot\":\"A special military unit fights a powerful, out-of-control supercomputer and hundreds of scientists who have mutated into flesh-eating creatures after a laboratory accident.\",\"Language\":\"English\",\"Country\":\"United Kingdom, Germany\",\"Awards\":\"7 nominations\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BZmI1ZGRhNDYtOGVjZC00MmUyLThlNTktMTQyZGE3MzE1ZTdlXkEyXkFqcGdeQXVyNDE5MTU2MDE@._V1_SX300.jpg\",\"Ratings\":[{ \"Source\":\"Internet Movie Database\",\"Value\":\"6.7/10\"},{ \"Source\":\"Rotten Tomatoes\",\"Value\":\"36%\"},{ \"Source\":\"Metacritic\",\"Value\":\"33/100\"}],\"Metascore\":\"33\",\"imdbRating\":\"6.7\",\"imdbVotes\":\"262,221\",\"imdbID\":\"tt0120804\",\"Type\":\"movie\",\"DVD\":\"07 Sep 2004\",\"BoxOffice\":\"$40,119,709\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"";
            string Resident02 = "\"Title\":\"Resident Evil: Apocalypse\",\"Year\":\"2004\",\"Rated\":\"R\",\"Released\":\"10 Sep 2004\",\"Runtime\":\"94 min\",\"Genre\":\"Action, Horror, Sci-Fi\",\"Director\":\"Alexander Witt\",\"Writer\":\"Paul W.S. Anderson\",\"Actors\":\"Milla Jovovich, Sienna Guillory, Eric Mabius\",\"Plot\":\"Alice wakes up in the Raccoon City hospital after the area has been overrun by zombies, and must now make it out of the city before a nuclear bomb is dropped.\",\"Language\":\"English\",\"Country\":\"Germany, United Kingdom, United States, Canada, France\",\"Awards\":\"6 wins & 3 nominations\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTc1NTUxMzk0Nl5BMl5BanBnXkFtZTcwNDQ1MDIzMw@@._V1_SX300.jpg\",\"Ratings\":[{ \"Source\":\"Internet Movie Database\",\"Value\":\"6.2/10\"},{ \"Source\":\"Rotten Tomatoes\",\"Value\":\"19%\"},{ \"Source\":\"Metacritic\",\"Value\":\"35/100\"}],\"Metascore\":\"35\",\"imdbRating\":\"6.2\",\"imdbVotes\":\"194,672\",\"imdbID\":\"tt0318627\",\"Type\":\"movie\",\"DVD\":\"19 Apr 2005\",\"BoxOffice\":\"$51,201,453\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"";
            string Resident03 = "\"Title\":\"Resident Evil: Extinction\",\"Year\":\"2007\",\"Rated\":\"R\",\"Released\":\"21 Sep 2007\",\"Runtime\":\"94 min\",\"Genre\":\"Action, Adventure, Horror\",\"Director\":\"Russell Mulcahy\",\"Writer\":\"Paul W.S. Anderson\",\"Actors\":\"Milla Jovovich, Ali Larter, Oded Fehr\",\"Plot\":\"Survivors of the Raccoon City catastrophe travel across the Nevada desert, hoping to make it to Alaska. Alice joins the caravan and their fight against the evil Umbrella Corp.\",\"Language\":\"English\",\"Country\":\"Germany\",\"Awards\":\"2 wins & 2 nominations\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNDQ0MWI3MmEtMzM0OC00Y2ViLWE4MDItMzNhNmY1ZTdjMWE2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\",\"Ratings\":[{ \"Source\":\"Internet Movie Database\",\"Value\":\"6.2/10\"},{ \"Source\":\"Rotten Tomatoes\",\"Value\":\"25%\"},{ \"Source\":\"Metacritic\",\"Value\":\"41/100\"}],\"Metascore\":\"41\",\"imdbRating\":\"6.2\",\"imdbVotes\":\"191,276\",\"imdbID\":\"tt0432021\",\"Type\":\"movie\",\"DVD\":\"01 Jan 2008\",\"BoxOffice\":\"$50,648,679\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"";
            string Resident04 = "\"Title\":\"Resident Evil: Afterlife\",\"Year\":\"2010\",\"Rated\":\"R\",\"Released\":\"10 Sep 2010\",\"Runtime\":\"96 min\",\"Genre\":\"Action, Adventure, Horror\",\"Director\":\"Paul W.S. Anderson\",\"Writer\":\"Paul W.S. Anderson\",\"Actors\":\"Milla Jovovich, Ali Larter, Wentworth Miller\",\"Plot\":\"While still out to destroy the evil Umbrella Corporation, Alice joins a group of survivors living in a prison surrounded by the infected who also want to relocate to the mysterious but supposedly unharmed safe haven known only as Arc\",\"Language\":\"English, Japanese, Spanish\",\"Country\":\"Germany, Canada\",\"Awards\":\"2 wins & 8 nominations\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BZjRlMGQ0NmUtM2U2Ny00MTk3LTg5NjAtN2M3Y2JmZjllNjJlXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg\",\"Ratings\":[{ \"Source\":\"Internet Movie Database\",\"Value\":\"5.8/10\"},{ \"Source\":\"Rotten Tomatoes\",\"Value\":\"21%\"},{ \"Source\":\"Metacritic\",\"Value\":\"37/100\"}],\"Metascore\":\"37\",\"imdbRating\":\"5.8\",\"imdbVotes\":\"168,476\",\"imdbID\":\"tt1220634\",\"Type\":\"movie\",\"DVD\":\"28 Dec 2010\",\"BoxOffice\":\"$60,128,566\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"";
            string Resident05 = "\"Title\":\"Resident Evil: Retribution\",\"Year\":\"2012\",\"Rated\":\"R\",\"Released\":\"14 Sep 2012\",\"Runtime\":\"95 min\",\"Genre\":\"Action, Adventure, Horror\",\"Director\":\"Paul W.S. Anderson\",\"Writer\":\"Paul W.S. Anderson\",\"Actors\":\"Milla Jovovich, Sienna Guillory, Michelle Rodriguez\",\"Plot\":\"Alice fights alongside a resistance movement to regain her freedom from an Umbrella Corporation testing facility.\",\"Language\":\"English, American Sign \",\"Country\":\"Germany, Canada\",\"Awards\":\"2 wins & 6 nominations\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BYmY0NjcwMWMtN2MyNC00ZmZjLWEwZTAtM2ExYWE1NDUwNWQyXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg\",\"Ratings\":[{ \"Source\":\"Internet Movie Database\",\"Value\":\"5.4/10\"},{ \"Source\":\"Rotten Tomatoes\",\"Value\":\"28%\"},{ \"Source\":\"Metacritic\",\"Value\":\"39/100\"}],\"Metascore\":\"39\",\"imdbRating\":\"5.4\",\"imdbVotes\":\"139,227\",\"imdbID\":\"tt1855325\",\"Type\":\"movie\",\"DVD\":\"21 Dec 2012\",\"BoxOffice\":\"$42,345,531\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"";
            string Resident06 = "\"Title\":\"Resident Evil: The Final Chapter\",\"Year\":\"2016\",\"Rated\":\"R\",\"Released\":\"27 Jan 2017\",\"Runtime\":\"107 min\",\"Genre\":\"Action, Adventure, Horror\",\"Director\":\"Paul W.S. Anderson\",\"Writer\":\"Paul W.S. Anderson\",\"Actors\":\"Milla Jovovich, Iain Glen, Ali Larter\",\"Plot\":\"Alice returns to where the nightmare began: The Hive in Raccoon City, where the Umbrella Corporation is gathering its forces for a final strike against the only remaining survivors of the apocalypse.\",\"Language\":\"English\",\"Country\":\"Germany, Canada\",\"Awards\":\"2 wins & 3 nominations\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTc0Mzc2OTQ0Ml5BMl5BanBnXkFtZTgwOTQ5MjE4MDI@._V1_SX300.jpg\",\"Ratings\":[{ \"Source\":\"Internet Movie Database\",\"Value\":\"5.5/10\"},{ \"Source\":\"Rotten Tomatoes\",\"Value\":\"37%\"},{ \"Source\":\"Metacritic\",\"Value\":\"49/100\"}],\"Metascore\":\"49\",\"imdbRating\":\"5.5\",\"imdbVotes\":\"90,628\",\"imdbID\":\"tt2592614\",\"Type\":\"movie\",\"DVD\":\"16 May 2017\",\"BoxOffice\":\"$26,830,068\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"";
            Movies.Add(Harry01);
            Movies.Add(Harry02);
            Movies.Add(Harry03);
            Movies.Add(Harry04);
            Movies.Add(Harry05);
            Movies.Add(Harry06);
            Movies.Add(Harry07);
            Movies.Add(Harry08);
            Movies.Add(Resident01);
            Movies.Add(Resident02);
            Movies.Add(Resident03);
            Movies.Add(Resident04);
            Movies.Add(Resident05);
            Movies.Add(Resident06);
            return Ok(Movies);
        }
    }
}